BOT_NAME = "YOUR_BOT_NAME"
BOT_TOKEN = "YOUR_BOT_TOKEN"

TRANSMISSION_USER = "YOUR_TRANSMISSION_USER"
TRANSMISSION_PASSWORD = "YOUR_TRANSMISSION_PASSWORD"

USER_ID_FILE = "user_id.dat"
LOGGING_CONFIG_FILE = "logging_config.json"
